version: "3.9"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: resttest_mysql
      MYSQL_USER: resttest
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  fastapi:
    build: .
    image: fastapi:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
#    volumes:
#      - ./:/code

volumes:
  mysql-data:
