
services:
  redis:
    image: redis:7
    container_name: redis-prod
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    build:
      context: .
      args:
        MODE: prod
    container_name: resttest-prod
    image: resttest-server
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    environment:
      - MODE=prod
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    depends_on:
      redis:
        condition: service_healthy