"""add monthly_study_date to user

Revision ID: 4e97dd8fe7e3
Revises: e41ef1fb1ba4
Create Date: 2025-06-15 10:21:57.464451
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4e97dd8fe7e3'
down_revision = 'e41ef1fb1ba4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column(
            'monthly_study_date',
            sa.JSON(),
            nullable=True,
            comment="학습한 날짜"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'monthly_study_date')
    # ### end Alembic commands ###