"""Initial migration

Revision ID: 836d47f3cbdc
Revises: 
Create Date: 2025-11-27 00:30:14.785515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '836d47f3cbdc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='자격증 고유 식별값'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='자격증 이름'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='사용자 고유 식별값'),
    sa.Column('auth_provider', sa.String(length=50), nullable=False, comment='소셜로그인 API 제공자'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='사용자 이메일'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='사용자 닉네임'),
    sa.Column('gender', sa.String(length=10), nullable=False, comment='사용자 성별'),
    sa.Column('birthday', sa.DateTime(), nullable=False, comment='사용자 생년월일'),
    sa.Column('job', sa.String(length=100), nullable=False, comment='사용자 직업'),
    sa.Column('agree_to_terms', sa.Boolean(), nullable=False, comment='선택약관 동의 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='계정 생성 일시'),
    sa.Column('studybook_limit', sa.Integer(), nullable=False, comment='나의 문제집 생성 제한 횟수'),
    sa.Column('rest_goal', sa.Integer(), nullable=True, comment='쉬엄모드 목표'),
    sa.Column('test_goal', sa.Integer(), nullable=True, comment='시험모드 목표'),
    sa.Column('profile_image', sa.String(length=255), nullable=True, comment='프로필 이미지 S3 URI'),
    sa.Column('total_study_days', sa.Integer(), nullable=False, comment='총 학습일'),
    sa.Column('monthly_study_date', mysql.JSON(), nullable=True, comment='학습한 날짜'),
    sa.Column('is_study_today', sa.Boolean(), nullable=False, comment='오늘 학습 여부'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='시험 고유 식별값'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='시험 이름'),
    sa.Column('pass_rate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='합격률'),
    sa.Column('year', sa.Integer(), nullable=False, comment='응시 년도'),
    sa.Column('month', sa.Integer(), nullable=False, comment='응시 월'),
    sa.Column('trial', sa.Integer(), nullable=True, comment='회차'),
    sa.Column('time', sa.Integer(), nullable=False, comment='시험 시간'),
    sa.Column('certificate_id', sa.BigInteger(), nullable=False, comment='자격증 ID'),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_note_by_rest',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='쉬엄모드 복습노트 고유 식별자'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='최초 생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='마지막 업데이트'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='복습노트 이름'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='사용자 ID'),
    sa.Column('certificate_id', sa.BigInteger(), nullable=False, comment='자격증 ID'),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificate.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studybook',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='나의 문제집 고유 식별자'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='문제집 생성일시'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='문제집 이름'),
    sa.Column('question_count', sa.Integer(), nullable=False, comment='문제 수'),
    sa.Column('file_color', sa.String(length=20), nullable=False, comment='파일 색상'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='사용자 고유 식별값'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('today_test',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='오늘의 문제 고유 식별자'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('is_solved', sa.Boolean(), nullable=False, comment='응시 완료 여부'),
    sa.Column('certificate_id', sa.BigInteger(), nullable=False, comment='자격증 ID'),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_certificate',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='사용자 고유 식별값'),
    sa.Column('certificate_id', sa.BigInteger(), nullable=False, comment='자격증 고유 식별값'),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificate.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'certificate_id')
    )
    op.create_table('exam_section',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='과목 고유 식별값'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='과목 명'),
    sa.Column('order', sa.Integer(), nullable=False, comment='과목 순서'),
    sa.Column('exam_id', sa.BigInteger(), nullable=False, comment='시험 고유 식별값'),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studybook_question',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='나의 문제집 문제 고유 식별자'),
    sa.Column('study_book_id', sa.BigInteger(), nullable=False, comment='문제집 ID'),
    sa.Column('description', sa.Text(), nullable=False, comment='문제 설명'),
    sa.Column('description_detail', sa.Text(), nullable=True, comment='문제 상세 설명'),
    sa.Column('description_image', sa.String(length=255), nullable=True, comment='문제 참고 이미지'),
    sa.Column('options', sa.JSON(), nullable=False, comment='문제 보기'),
    sa.Column('answer', sa.Integer(), nullable=False, comment='정답'),
    sa.Column('option_explanations', sa.JSON(), nullable=True, comment='보기 별 해설'),
    sa.ForeignKeyConstraint(['study_book_id'], ['studybook.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_tracker',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='시험 기록 고유 식별값'),
    sa.Column('exam_id', sa.BigInteger(), nullable=False, comment='시험 ID'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='사용자 ID'),
    sa.Column('is_passed', sa.Boolean(), nullable=False, comment='통과 여부'),
    sa.Column('solved_at', sa.DateTime(), nullable=False, comment='응시 일시'),
    sa.Column('score', sa.Integer(), nullable=False, comment='점수'),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('today_test_question',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='오늘의 문제 질문 고유 식별자'),
    sa.Column('today_test_by_ai_id', sa.BigInteger(), nullable=False, comment='오늘의 문제 ID'),
    sa.Column('description', sa.Text(), nullable=False, comment='문제 설명'),
    sa.Column('description_detail', sa.Text(), nullable=True, comment='문제 상세 설명'),
    sa.Column('options', sa.JSON(), nullable=False, comment='보기 목록'),
    sa.Column('answer', sa.Integer(), nullable=False, comment='정답'),
    sa.Column('option_explanations', sa.JSON(), nullable=False, comment='보기별 해설'),
    sa.ForeignKeyConstraint(['today_test_by_ai_id'], ['today_test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='문제 고유 식별자'),
    sa.Column('answer_rate', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='정답률'),
    sa.Column('section', sa.String(length=50), nullable=False, comment='문제 분류'),
    sa.Column('description', sa.Text(), nullable=False, comment='문제 설명'),
    sa.Column('description_detail', sa.Text(), nullable=True, comment='문제 상세 설명'),
    sa.Column('description_image', sa.String(length=255), nullable=True, comment='문제 참고 이미지'),
    sa.Column('options', sa.JSON(), nullable=False, comment='문제 보기'),
    sa.Column('answer', sa.Integer(), nullable=False, comment='정답'),
    sa.Column('option_explanations', sa.JSON(), nullable=False, comment='보기 별 해설'),
    sa.Column('exam_id', sa.BigInteger(), nullable=False, comment='시험 ID'),
    sa.Column('exam_section_id', sa.BigInteger(), nullable=False, comment='과목 고유 식별값'),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['exam_section_id'], ['exam_section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_note_by_test',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='복습노트 고유 식별자'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='사용자 ID'),
    sa.Column('study_tracker_id', sa.BigInteger(), nullable=False, comment='시험 기록 ID'),
    sa.ForeignKeyConstraint(['study_tracker_id'], ['test_tracker.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_note_by_rest_question',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='쉬엄모드 복습노트 문제 고유 식별자'),
    sa.Column('selected_answer', sa.Integer(), nullable=True, comment='사용자가 선택한 답'),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='정답 여부'),
    sa.Column('added_at', sa.DateTime(), nullable=False, comment='추가된 일시'),
    sa.Column('review_note_by_rest_id', sa.BigInteger(), nullable=False, comment='복습노트 ID'),
    sa.Column('question_id', sa.BigInteger(), nullable=False, comment='문제 ID'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['review_note_by_rest_id'], ['review_note_by_rest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_question_tracker',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='시험 질문 응답 고유 식별값'),
    sa.Column('study_tracker_id', sa.BigInteger(), nullable=False, comment='시험 기록 ID'),
    sa.Column('question_id', sa.BigInteger(), nullable=False, comment='문제 ID'),
    sa.Column('selected_answer', sa.Integer(), nullable=True, comment='선택한 답'),
    sa.Column('is_correct', sa.Boolean(), nullable=False, comment='정답 여부'),
    sa.Column('add_to_review', sa.Boolean(), nullable=False, comment='리뷰노트 등록 여부'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['study_tracker_id'], ['test_tracker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_question_tracker')
    op.drop_table('review_note_by_rest_question')
    op.drop_table('review_note_by_test')
    op.drop_table('question')
    op.drop_table('today_test_question')
    op.drop_table('test_tracker')
    op.drop_table('studybook_question')
    op.drop_table('exam_section')
    op.drop_table('user_certificate')
    op.drop_table('today_test')
    op.drop_table('studybook')
    op.drop_table('review_note_by_rest')
    op.drop_table('exam')
    op.drop_table('user')
    op.drop_table('certificate')
    # ### end Alembic commands ###
