"""update migration

Revision ID: f79d27850cb1
Revises: 
Create Date: 2025-11-30 23:50:16.337133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f79d27850cb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'explanations')
    op.drop_column('studybook_question', 'explanation')
    op.create_index(op.f('ix_user_today_test_id'), 'user_today_test', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_today_test_id'), table_name='user_today_test')
    op.add_column('studybook_question', sa.Column('explanation', mysql.LONGTEXT(), nullable=True, comment='문제 해설'))
    op.add_column('question', sa.Column('explanations', mysql.TEXT(), nullable=True, comment='전체 해설'))
    # ### end Alembic commands ###
